site_name: hyperify.io
site_url: https://www.hyperify.io/
site_author: Sendanor
remote_branch: master
docs_dir: src
site_dir: docs
copyright: Copyright (c) 2007-2023 <a href="mailto:info@sendanor.com">Sendanor</a>, FI-20925406
theme:
  name: readthedocs
  locale: en
plugins:
- search:
    min_search_length: 2
    indexing: 'full'
- mermaid2
extra_css:
- stylesheets/extra.css
nav:
- 'About': 'index.md'
markdown_extensions:
- meta
- attr_list
- pymdownx.tabbed
- toc:
    permalink: true
    slugify: !!python/name:pymdownx.slugs.uslugify
- pymdownx.superfences:
    # make exceptions to highlighting of code:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:mermaid2.fence_mermaid
extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/sendanor
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/company/sendanor/
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/sendanorcom
  - icon: fontawesome/brands/discord
    link: https://discord.gg/dVTpkTh
  - icon: fontawesome/brands/facebook
    link: https://www.facebook.com/sendanor/
